name: Continuous Integration

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Install tailwindcss CLI
      run: |
        curl -L -o tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.13/tailwindcss-linux-x64
        chmod +x tailwindcss
        sudo mv tailwindcss /usr/local/bin/

    - name: Install dependencies
      run: make setup

    - name: Run tests
      run: make test